FROM postgres:16

ARG WALG_VERSION=v3.0.8
ARG WALG_URL=https://github.com/wal-g/wal-g/releases/download/${WALG_VERSION}/wal-g-pg-22.04-amd64

RUN apt-get update && apt-get install -y --no-install-recommends wget ca-certificates \
    && wget -q "${WALG_URL}" -O /usr/local/bin/wal-g \
    && chmod +x /usr/local/bin/wal-g \
    && apt-get remove -y wget \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*
